# Generated by Django 2.2 on 2020-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200414_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='recommended',
            field=models.IntegerField(choices=[(2, '及格'), (4, '优秀'), (1, '较差'), (5, '经典'), (3, '良好')], default=2, max_length=2, verbose_name='推荐指数'),
        ),
    ]
