# Generated by Django 2.2 on 2020-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_courseorg_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='recommended',
            field=models.IntegerField(choices=[(5, '经典'), (1, '较差'), (4, '优秀'), (2, '及格'), (3, '良好')], default=2, max_length=4, verbose_name='推荐指数'),
        ),
    ]
