# Generated by Django 2.2 on 2020-05-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200507_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='recommended',
            field=models.IntegerField(choices=[(4, '优秀'), (5, '经典'), (1, '较差'), (3, '良好'), (2, '及格')], default=2, verbose_name='推荐指数'),
        ),
    ]
